### ISSUE TITLE
Incorrect config paths

### ISSUE THREAD

**Issue by fsimkovic** [soedinglab/bbcontacts#3]
Commit b273931451b0d794d13683afde422764cb72803b created a bug on my Ubuntu machine.  

```
adenine: felix: ~/develop/bbcontacts > bbcontacts example/1nz0D.mat 0.376 1nz0D -p example/1nz0D.psipred
/home/felix/anaconda/lib/python2.7/site-packages/bbcontacts-1.0-py2.7.egg/bbcontacts

Starting run 1nz0D 0.376
Traceback (most recent call last):
  File "/home/felix/anaconda/bin/bbcontacts", line 9, in <module>
    load_entry_point('bbcontacts', 'console_scripts', 'bbcontacts')()
  File "/home/felix/anaconda/lib/python2.7/site-packages/bbcontacts-1.0-py2.7.egg/bbcontacts/main.py", line 146, in main
    secprobdic = paramshmm.getSecondaryStructureProbabilities(condsecstructprobPSIPREDfile)
  File "/home/felix/anaconda/lib/python2.7/site-packages/bbcontacts-1.0-py2.7.egg/bbcontacts/hmm/paramshmm.py", line 58, in getSecondaryStructureProbabilities
    with open(inputfile,"r") as f:
IOError: [Errno 2] No such file or directory: '/home/felix/anaconda/lib/python2.7/site-packages/bbcontacts-1.0-py2.7.egg/bbcontacts/bbcontacts/paramfiles/secondaryStructureProbabilities_PSIPRED_conditionalwith10000pseudocounts.txt'
```

I think the paths should be `paramfiles/secondaryStructureProbabilities_PSIPRED_conditionalwith10000pseudocounts.txt`.

Do you observe the same issue @jessica-andreani ?

**Comment by jessica-andreani** [comment]
Well I had to edit the file, because I was observing the exact opposite issue...

**Comment by fsimkovic** [comment]
Not sure why this is happening on your computer but my Linux and OS X machines both require the pre-commit version.

I've tried removing all existing version and then reinstalled it. The problem persists until I make the aforementioned changes. The commands I used to reinstall were

```
pip uninstall bbcontacts
python setup.py install
```

**Comment by jessica-andreani** [comment]
The issue I was originally observing happened when using the -c option, because paths for the parameter files were not set as relative to the config file. I updated the code and config file with commit ec7d724.
@fsimkovic can you please check that this solves the issue and that both example command lines in the README (without or with -c option) work for you?

**Comment by fsimkovic** [comment]
Thanks @jessica-andreani. Both example command lines work!
